# Generated by Django 2.2 on 2019-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='git_hub',
            field=models.URLField(blank=True, null=True, verbose_name='Github'),
        ),
    ]
