# Generated by Django 2.2 on 2019-09-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taks_status',
            new_name='task_status',
        ),
    ]
