# Generated by Django 2.2 on 2019-10-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0005_auto_20191011_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Закрытый')], default='active',
                                   max_length=20),
        ),
    ]
