# Generated by Django 2.2 on 2019-11-03 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_project', to='webapp.Project', verbose_name='Проект')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
