# Generated by Django 2.2 on 2019-11-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0007_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
