# Generated by Django 2.2 on 2019-11-14 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0008_auto_20191114_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('can_change_team', 'Can Change Team'),)},
        ),
    ]
